#' CMHC Data Abbreviations
#'
#' This named list provides a mapping of original CMHC variable names to standardized abbreviations. 
#' The abbreviations are used to shorten column and table names for improved readability and usability
#' The list is structured as `original_variable_name = "abbreviation"`, 
  
cmhc_data_abbreviations <- list(
  # Original CMHC variable names and their corresponding abbreviations
  "starts_dwelling_type_single" = "st_dt_sgl",
  "starts_dwelling_type_semi_detached" = "st_dt_semi",
  "starts_dwelling_type_row" = "st_dt_rw",
  "starts_dwelling_type_apartment" = "st_dt_apt",
  "starts_dwelling_type_all" = "st_dt_all",
  "starts_intended_market_unknown" = "st_im_unk",
  "starts_intended_market_homeowner" = "st_im_hm",
  "starts_intended_market_rental" = "st_im_rnt",
  "starts_intended_market_condo" = "st_im_cnd",
  "starts_intended_market_co_op" = "st_im_coop",
  "starts_intended_market_all" = "st_im_all",
  "starts_saar" = "st_saar",
  
  "completions_dwelling_type_single" = "comp_dt_sgl",
  "completions_dwelling_type_semi_detached" = "comp_dt_semi",
  "completions_dwelling_type_row" = "comp_dt_rw",
  "completions_dwelling_type_apartment" = "comp_dt_apt",
  "completions_dwelling_type_all" = "comp_dt_all",
  "completions_intended_market_homeowner" = "comp_im_hm",
  "completions_intended_market_rental" = "comp_im_rnt",
  "completions_intended_market_condo" = "comp_im_cnd",
  "completions_intended_market_co_op" = "comp_im_coop",
  "completions_intended_market_all" = "comp_im_all",
  
  "under_construction_dwelling_type_single" = "uc_dt_sgl",
  "under_construction_dwelling_type_semi_detached" = "uc_dt_semi",
  "under_construction_dwelling_type_row" = "uc_dt_rw",
  "under_construction_dwelling_type_apartment" = "uc_dt_apt",
  "under_construction_dwelling_type_all" = "uc_dt_all",
  "under_construction_intended_market_unknown" = "uc_im_unk",
  "under_construction_intended_market_homeowner" = "uc_im_hm",
  "under_construction_intended_market_rental" = "uc_im_rnt",
  "under_construction_intended_market_condo" = "uc_im_cnd",
  "under_construction_intended_market_co_op" = "uc_im_coop",
  "under_construction_intended_market_all" = "uc_im_all",
  
  "length_of_construction_dwelling_type_single" = "lc_dt_sgl",
  "length_of_construction_dwelling_type_semi_detached" = "lc_dt_semi",
  "length_of_construction_dwelling_type_row" = "lc_dt_rw",
  "length_of_construction_dwelling_type_apartment" = "lc_dt_apt",
  "length_of_construction_dwelling_type_all" = "lc_dt_all",
  "length_of_construction_intended_market_homeowner" = "lc_im_hm",
  "length_of_construction_intended_market_rental" = "lc_im_rnt",
  "length_of_construction_intended_market_condo" = "lc_im_cnd",
  "length_of_construction_intended_market_co_op" = "lc_im_coop",
  "length_of_construction_intended_market_all" = "lc_im_all",
  
  "share_absorbed_at_completion_dwelling_type_single" = "sac_dt_sgl",
  "share_absorbed_at_completion_dwelling_type_semi_detached" = "sac_dt_semi",
  "share_absorbed_at_completion_dwelling_type_row" = "sac_dt_rw",
  "share_absorbed_at_completion_dwelling_type_apartment" = "sac_dt_apt",
  "share_absorbed_at_completion_dwelling_type_all" = "sac_dt_all",
  
  "vacancy_rate_bedroom_type_bachelor" = "vacr_bt_bach",
  "vacancy_rate_bedroom_type_1_bedroom" = "vacr_bt_1bd",
  "vacancy_rate_bedroom_type_2_bedroom" = "vacr_bt_2bd",
  "vacancy_rate_bedroom_type_3_bedroom" = "vacr_bt_3bd",
  "vacancy_rate_bedroom_type_total" = "vacr_bt_all",
  "vacancy_rate_year_of_construction_before_1960" = "vacr_yc_b60",
  "vacancy_rate_year_of_construction_1960_1979" = "vacr_yc_60_79",
  "vacancy_rate_year_of_construction_1980_1999" = "vacr_yc_80_99",
  "vacancy_rate_year_of_construction_2000_or_later" = "vacr_yc_2000",
  "vacancy_rate_year_of_construction_total" = "vacr_yc_all",
  "vacancy_rate_structure_size_3_5_units" = "vacr_sz_3_5u",
  "vacancy_rate_structure_size_6_19_units" = "vacr_sz_6_19u",
  "vacancy_rate_structure_size_20_49_units" = "vacr_sz_20_49u",
  "vacancy_rate_structure_size_50_199_units" = "vacr_sz_50_199u",
  "vacancy_rate_structure_size_total" = "vacr_sz_all",
  "vacancy_rate_rent_ranges_less_than_750" = "vacr_rr_lt750",
  "vacancy_rate_rent_ranges_750_999" = "vacr_rr_750_999",
  "vacancy_rate_rent_ranges_1_000_1_249" = "vacr_rr_1000_1250",
  "vacancy_rate_rent_ranges_1_250_1_499" = "vacr_rr_1250_1500",
  "vacancy_rate_rent_ranges_1_500" = "vacr_rr_1500",
  "vacancy_rate_rent_ranges_non_market_unknown" = "vacr_rr_nmunk",
  "vacancy_rate_rent_ranges_total" = "vacr_rr_all",
  
  "average_rent_bedroom_type_bachelor" = "avgr_bt_bach",
  "average_rent_bedroom_type_1_bedroom" = "avgr_bt_1bd",
  "average_rent_bedroom_type_2_bedroom" = "avgr_bt_2bd",
  "average_rent_bedroom_type_3_bedroom" = "avgr_bt_3bd",
  "average_rent_bedroom_type_total" = "avgr_bt_all",
  "average_rent_year_of_construction_before_1960" = "avgr_yc_b60",
  "average_rent_year_of_construction_1960_1979" = "avgr_yc_60_79",
  "average_rent_year_of_construction_1980_1999" = "avgr_yc_80_99",
  "average_rent_year_of_construction_2000_or_later" = "avgr_yc_2000",
  "average_rent_year_of_construction_total" = "avgr_yc_all",
  "average_rent_structure_size_3_5_units" = "avgr_sz_3_5u",
  "average_rent_structure_size_6_19_units" = "avgr_sz_6_19u",
  "average_rent_structure_size_20_49_units" = "avgr_sz_20_49u",
  "average_rent_structure_size_50_199_units" = "avgr_sz_50_199u",
  "average_rent_structure_size_total" = "avgr_sz_all",
  
  "median_rent_bedroom_type_bachelor" = "medr_bt_bach",
  "median_rent_bedroom_type_1_bedroom" = "medr_bt_1bd",
  "median_rent_bedroom_type_2_bedroom" = "medr_bt_2bd",
  "median_rent_bedroom_type_3_bedroom" = "medr_bt_3bd",
  "median_rent_bedroom_type_total" = "medr_bt_all",
  "median_rent_year_of_construction_before_1960" = "medr_yc_b60",
  "median_rent_year_of_construction_1960_1979" = "medr_yc_60_79",
  "median_rent_year_of_construction_1980_1999" = "medr_yc_80_99",
  "median_rent_year_of_construction_2000_or_later" = "medr_yc_2000",
  "median_rent_year_of_construction_total" = "medr_yc_all",
  "median_rent_structure_size_3_5_units" = "medr_sz_3_5u",
  "median_rent_structure_size_6_19_units" = "medr_sz_6_19u",
  "median_rent_structure_size_20_49_units" = "medr_sz_20_49u",
  "median_rent_structure_size_50_199_units" = "medr_sz_50_199u",
  "median_rent_structure_size_total" = "medr_sz_all",
  
  "rental_universe_bedroom_type_bachelor" = "ru_bt_bach",
  "rental_universe_bedroom_type_1_bedroom" = "ru_bt_1bd",
  "rental_universe_bedroom_type_2_bedroom" = "ru_bt_2bd",
  "rental_universe_bedroom_type_3_bedroom" = "ru_bt_3bd",
  "rental_universe_bedroom_type_total" = "ru_bt_all",
  "rental_universe_year_of_construction_before_1960" = "ru_yc_b60",
  "rental_universe_year_of_construction_1960_1979" = "ru_yc_60_79",
  "rental_universe_year_of_construction_1980_1999" = "ru_yc_80_99",
  "rental_universe_year_of_construction_2000_or_later" = "ru_yc_2000",
  "rental_universe_year_of_construction_total" = "ru_yc_all",
  "rental_universe_structure_size_3_5_units" = "ru_sz_3_5u",
  "rental_universe_structure_size_6_19_units" = "ru_sz_6_19u",
  "rental_universe_structure_size_20_49_units" = "ru_sz_20_49u",
  "rental_universe_structure_size_50_199_units" = "ru_sz_50_199u",
  "rental_universe_structure_size_total" = "ru_sz_all",
  "vacancy_rate_structure_size_200_units" = "vacr_sz_200u",
  "average_rent_structure_size_200_units" = "avgr_sz_200u",
  "median_rent_structure_size_200_units" = "medr_sz_200u",
  "rental_universe_structure_size_200_units" = "ru_sz_200u"
)

usethis::use_data(cmhc_data_abbreviations, overwrite = TRUE)